# frozen_string_literal: true

require_relative 'support/local_vertex_normalizer_test_support'
require_relative 'local_vertex_normalizer/operations_and_axis'
require_relative 'local_vertex_normalizer/mesh_repair'
require_relative 'local_vertex_normalizer/sliver_repair'
require_relative 'local_vertex_normalizer/patch_triangulation'
