# frozen_string_literal: true

# Loads the LocalVertexNormalizer kernel and its v2 policies in dependency order.
require_relative 'local_vertex_normalizer/legacy_kernel'
require_relative 'local_vertex_normalizer/coplanar_shared_edge_groups'
require_relative 'local_vertex_normalizer/pipeline_v2'
require_relative 'local_vertex_normalizer/runtime_regression_fixes_v2'
require_relative 'local_vertex_normalizer/topology_preserving_grid_targets_v2'
require_relative 'local_vertex_normalizer/global_shell_embedding_grid_targets_v2'
require_relative 'local_vertex_normalizer/source_face_boundary_constraints_v2'
require_relative 'local_vertex_normalizer/source_face_boundary_common_refinement_v2'
require_relative 'local_vertex_normalizer/source_face_boundary_unique_loop_insertions_v2'
require_relative 'local_vertex_normalizer/source_face_boundary_common_refinement_topology_v2'
require_relative 'local_vertex_normalizer/topology_grid_target_beam_search_v2'
require_relative 'local_vertex_normalizer/final_boundary_conformity_repair_v2'
require_relative 'local_vertex_normalizer/rebuilt_surface_checkpoint_v2'
require_relative 'local_vertex_normalizer/validated_rebuild_triangulation_preservation_v2'
require_relative 'local_vertex_normalizer/surface_preserving_rebuilt_entity_repair_v2'
