name: Deploy Extension

on:
  workflow_dispatch:
    inputs:
      visibility:
        type: choice
        required: true
        default: visible
        options: [visible, hidden]

      distribution:
        type: choice
        required: true
        default: preview
        options: [active, preview, deprecated, disabled]

  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  deploy:
    uses: UlolSkpProject/ULOL-Extension-Repository/.github/workflows/deploy-extension.yml@main
    with:
      extension_id: indoor3d
      loader_file: indoor3d.rb
      visibility: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.visibility || '' }}
      distribution: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.distribution || '' }}
      category: SeoulSpace
      release_note_url: "https://u-lo-l.notion.site/Indoor-Modeler-35fbe883973b80d1be3be90372b712ed?source=copy_link"
    secrets:
      DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
