name: Deploy Extension

on:
  workflow_dispatch:
    inputs:
      visibility:
        type: choice
        required: true
        default: visible
        options: [visible, hidden]

      distribution:
        type: choice
        required: true
        default: active
        options: [active, preview, deprecated, disabled]

permissions:
  contents: write

jobs:
  deploy:
    uses: UlolSkpProject/ULOL-Extension-Repository/.github/workflows/deploy-extension.yml@main
    with:
      extension_id: indoor3d # <-여기
      loader_file: indoor3d.rb # <-여기
      visibility: ${{ github.event.inputs.visibility }}
      distribution: ${{ github.event.inputs.distribution }}
    secrets:
      DEPLOY_REPO_TOKEN: ${{ secrets.DEPLOY_REPO_TOKEN }}